[package]
name = 'LiquidswapLP'
version = '1.0.0'
upgrade_policy = "immutable"

[addresses]
liquidswap_lp = "0xcd09213f25e3312923acfd64149b2f5653dd2ff3157ed9d8e0f4f645f83a0926"

[dev-dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a2a3bf79b68823287f962bded2abfaefc688e71c"
subdir = "aptos-move/framework/move-stdlib"
