[package]
name = 'LiquidswapInit'
version = '1.0.0'
upgrade_policy = "immutable"

[addresses]
liquidswap = "0xb1bd5326bd07334bbba68aac7b8fb74478c6ccfaae07a0236884dd053e8cde48"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a2a3bf79b68823287f962bded2abfaefc688e71c"
subdir = "aptos-move/framework/aptos-framework"
